name: Nextail
favicon: null
layout_spectrum: 0.411205644486472
typography_spectrum: 0.9266604867298156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8083881032653153
  lightness: 0.7884271685034037
  saturation: 0.05386201408691704
  rhythmicContrast: 0.18921840679831803
purpose: []
